"""add cleaning and other charges to invoice

Revision ID: 427f310b3c52
Revises: 72dd537b2fc9
Create Date: 2026-03-04 18:10:07.555337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427f310b3c52'
down_revision: Union[str, Sequence[str], None] = '72dd537b2fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('cleaning_charge', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('other_charges', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'other_charges')
    op.drop_column('invoices', 'cleaning_charge')
    # ### end Alembic commands ###
