"""add cleaning and other charges to room

Revision ID: 6e1c4079e008
Revises: 6c650cd38575
Create Date: 2026-03-04 17:37:25.259957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1c4079e008'
down_revision: Union[str, Sequence[str], None] = '6c650cd38575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('cleaning_charge', sa.Float(), nullable=True))
    op.add_column('rooms', sa.Column('other_charges', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'other_charges')
    op.drop_column('rooms', 'cleaning_charge')
    # ### end Alembic commands ###
