"""add global charges to property

Revision ID: 72dd537b2fc9
Revises: a41fa3e9c148
Create Date: 2026-03-04 18:05:40.384055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dd537b2fc9'
down_revision: Union[str, Sequence[str], None] = 'a41fa3e9c148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('water_charge', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('cleaning_charge', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('other_charges', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'other_charges')
    op.drop_column('properties', 'cleaning_charge')
    op.drop_column('properties', 'water_charge')
    # ### end Alembic commands ###
