"""add tenant_name to room

Revision ID: a41fa3e9c148
Revises: 6e1c4079e008
Create Date: 2026-03-04 18:00:32.958100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41fa3e9c148'
down_revision: Union[str, Sequence[str], None] = '6e1c4079e008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('tenant_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'tenant_name')
    # ### end Alembic commands ###
